version: '3'

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    volumes:
      - ./db/data:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./server/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node-app
